In [61]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL
from urllib.parse import unquote

server_name   = "localhost"
database_name = "Bokhandel"

connection_string = f"DRIVER=ODBC Driver 17 for SQL Server;SERVER={server_name};DATABASE={database_name};Trusted_Connection=yes"
url_string        = URL.create("mssql+pyodbc", query={"odbc_connect": connection_string})

In [63]:
from sqlalchemy import create_engine, text

# Create the database connection
db_url = 'your_database_url'
engine = create_engine(url_string)
connection = engine.connect()

def search_books_by_title(title):
    # Perform a free-text search on book titles
    query = text("SELECT Titel, LagerSaldoo.ButikID, LagerSaldoo.Antal "
                 "FROM Böcker "
                 "JOIN LagerSaldoo ON Böcker.ISBN13 = LagerSaldoo.ISBN "
                 "WHERE Titel LIKE :title")
    result = connection.execute(query, {'title': f'%{title}%'})

    # Print the matching books and their stock balances
    for row in result:
        book_title = row[0]  # Accessing the first column (Titel) by index
        store_id = row[1]    # Accessing the second column (ButikID) by index
        stock_balance = row[2]  # Accessing the third column (Antal) by index
        print(f"Title: {book_title}, Store ID: {store_id}, Stock Balance: {stock_balance}")

# Main program loop
while True:
    user_input = input("Enter a book title to search (or 'exit' to quit): ")
    if user_input == 'exit':
        break
    search_books_by_title(user_input)

# Close the database connection
connection.close()

Title: Tjänarinnans berättelse
, Store ID: 7, Stock Balance: 6
Title: En kvinnas själ
, Store ID: 8, Stock Balance: 7
Title: Dolken från Tunis
, Store ID: 10, Stock Balance: 4
Title: Beloved, Store ID: 1, Stock Balance: 4
Title: 1984, Store ID: 2, Stock Balance: 1
Title: War And Peace
, Store ID: 3, Stock Balance: 5
Title: Victory City
, Store ID: 4, Stock Balance: 6
Title: Animal Farm
, Store ID: 5, Stock Balance: 2
Title: Anna Karenina, Store ID: 6, Stock Balance: 4
Title: Tjänarinnans berättelse
, Store ID: 7, Stock Balance: 6
Title: En kvinnas själ
, Store ID: 8, Stock Balance: 7
Title: Goda omen
, Store ID: 9, Stock Balance: 8
Title: Dolken från Tunis
, Store ID: 10, Stock Balance: 4
Title: Beloved, Store ID: 1, Stock Balance: 4
Title: 1984, Store ID: 2, Stock Balance: 1
Title: War And Peace
, Store ID: 3, Stock Balance: 5
Title: Victory City
, Store ID: 4, Stock Balance: 6
Title: Animal Farm
, Store ID: 5, Stock Balance: 2
Title: Anna Karenina, Store ID: 6, Stock Balance: 4
Title: Tjänarinnans berättelse
, Store ID: 7, Stock Balance: 6
Title: En kvinnas själ
, Store ID: 8, Stock Balance: 7
Title: Goda omen
, Store ID: 9, Stock Balance: 8
Title: Dolken från Tunis
, Store ID: 10, Stock Balance: 4
Title: Beloved, Store ID: 1, Stock Balance: 4
Title: 1984, Store ID: 2, Stock Balance: 1
Title: War And Peace
, Store ID: 3, Stock Balance: 5
Title: Victory City
, Store ID: 4, Stock Balance: 6
Title: Animal Farm
, Store ID: 5, Stock Balance: 2
Title: Anna Karenina, Store ID: 6, Stock Balance: 4
Title: Tjänarinnans berättelse
, Store ID: 7, Stock Balance: 6
Title: En kvinnas själ
, Store ID: 8, Stock Balance: 7
Title: Goda omen
, Store ID: 9, Stock Balance: 8
Title: Dolken från Tunis
, Store ID: 10, Stock Balance: 4
Title: Beloved, Store ID: 1, Stock Balance: 4
Title: 1984, Store ID: 2, Stock Balance: 1
Title: War And Peace
, Store ID: 3, Stock Balance: 5
Title: Victory City
, Store ID: 4, Stock Balance: 6
Title: Animal Farm
, Store ID: 5, Stock Balance: 2
Title: Anna Karenina, Store ID: 6, Stock Balance: 4
Title: Tjänarinnans berättelse
, Store ID: 7, Stock Balance: 6
Title: En kvinnas själ
, Store ID: 8, Stock Balance: 7
Title: Goda omen
, Store ID: 9, Stock Balance: 8
Title: Dolken från Tunis
, Store ID: 10, Stock Balance: 4